joint_limits:
  joint0_shoulder_pan:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: true
    max_acceleration: 3.785
  joint1_shoulder_lift:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: true
    max_acceleration: 3.785
  joint2_elbow:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: true
    max_acceleration: 3.785
  joint3_index_finger:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: true
    max_acceleration: 3.785
  joint4_middle_finger:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.785
